### ISSUE TITLE
`localhost:27017: connection pool paused` when connecting over gunicorn

### ISSUE THREAD

**Issue by signebedi** [signebedi/libreForms#128]
When trying to submit forms when connected to a gunicorn-enabled production system, we receive a `localhost:27017: connection pool paused` error flashed on the screen - though it doesn't cause the system to fail, which suggests it's contained in a try/except construction.

I think that this might be caused by leaving multiple mongodb connections open at the same time, see (1) below. This can probably be solved with some boilerplate to connect to / close connections to mongodb after each read  / write ... possibly within a `with` statement, eg.

```python
with pymongo.MongoClient(db_config['HOST']) as client:
    db = client[ db_config['NAME']]
    item = db["document"].find_one({'id':1})
    print(item)
```

Reference:
1. https://stackoverflow.com/a/73169147
2. https://stackoverflow.com/a/18401169

**Comment by signebedi** [comment]
Authentication problem also, when we turn on authorization:
```
2022-12-03 06:39:09 - ERROR - Exception on /dashboards/request [GET] - 5815
Traceback (most recent call last):
  File "/opt/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/libreForms/venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/opt/libreForms/app/dashboards.py", line 54, in dashboards
    data = mongodb.read_documents_from_collection(form_name)
  File "/opt/libreForms/app/mongo.py", line 133, in read_documents_from_collection
    return list(collection.find())
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1165, in _refresh
    self.__send_message(q)
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1052, in __send_message
    response = client._run_operation(
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1267, in _run_operation
    return self._retryable_read(
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1365, in _retryable_read
    with self._socket_from_server(read_pref, server, session) as (sock_info, read_pref):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1221, in _socket_from_server
    with self._get_socket(server, session) as sock_info:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1156, in _get_socket
    with server.get_socket(handler=err_handler) as sock_info:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/pool.py", line 1379, in get_socket
    sock_info = self._get_socket()
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/pool.py", line 1489, in _get_socket
    sock_info = self.connect()
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/pool.py", line 1350, in connect
    sock_info.authenticate()
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/pool.py", line 845, in authenticate
    auth.authenticate(creds, self)
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/auth.py", line 549, in authenticate
    auth_func(credentials, sock_info)
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/auth.py", line 475, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, "SCRAM-SHA-1")
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/auth.py", line 201, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/pool.py", line 743, in command
    return command(
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/network.py", line 160, in command
    helpers._check_command_response(
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pymongo/helpers.py", line 180, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}

```
