### ISSUE TITLE
Fix bug with upstream keys in `generate_full_document_history()`

### ISSUE THREAD

**Issue by signebedi** [signebedi/libreForms#145]
Right now we have a function that generates a document history. But, if we add a field later, but not in the initial submission, then it does not add them to the dictionary keys of earlier forms - such that it does not render the prettified approval signature.

```python
# Right now, each document submission stores a full carbon copy of the initial submission in 
# the `Journal`, and then just a summary of the changes in each subsequent change. There are 
# good cases to be made for this approach, as well as for the alternative approach of storing 
# a **complete** new copy  under journal each time a change is made. I think it makes sense 
# to just store subsequent changes because it allows us to highlight DIFFs pretty easily. In 
# addition, it minimizes sprawl and complexity in the data structure. That said, to accomplish 
# this objective of this issue, I needed to work around the limitations of this changes-only 
# approach -- namely, that it's hard to construct a full document from a reference to changes 
# only. So I wrote the following method to 'expand' the `Journal` data structure, see 
# https://github.com/signebedi/libreForms/issues/91 for more information about this.

def generate_full_document_history(form, document_id, user=None):
    try:
        df = get_record_of_submissions(form, user=user if user else None) # here we get the list of entries

        record = df.loc[df.id == document_id] # here we search for the document ID

        history = dict(record[['Journal']].iloc[0].values[0]) # here we pull out the document history

        # dates of new submissions are used as the unique keys in each Journal entry for a form,
        # so we create a list 
        dates = [x for x in history.keys()] 
                
        # now we create a replacement dictionary that will store the full document history in memory, 
        # even though we stored the bare minimum in the database.
        FULL_HISTORY = {}

        # this is an ephemeral dictionary that we are we will re-write each time with the most recent 
        # version. At the time of writing, this seemed like the most efficient way to accomplish what
        # I'm trying to do without iterating through each array / hash multiple times to expand them... 
        BASE_HISTORY = {}

        # the first entry of each Journal contains a full replica of the original submission, so we
        # start with it here to set a baseline
        FULL_HISTORY[dates[0]] = history[dates[0]].copy()

        # we previously added back in the timestamp (and did it again later for subsequent entries in the
        # document history) - is it worth the extra computation requirement to avoid redundance in adding
        # Timestamp field multiple times? See https://github.com/signebedi/libreForms/issues/140.
        # FULL_HISTORY[dates[0]]['Timestamp'] = dates[0]

        # delete the initial_submission key if it exists; it's redundant here and can probably be deprecated.
        # Nb. This line of code was made redundant by https://github.com/signebedi/libreForms/issues/141.
        # if checkKey(FULL_HISTORY[dates[0]], 'initial_submission'): del FULL_HISTORY[dates[0]]['initial_submission']

        # create an initial carbon copy in BASE_HISTORY - remember, this isn't the for-record dictionary,
        # we're just using it to store the current values of each Journal entry as we iterate through them
        # and expand them.
        BASE_HISTORY = FULL_HISTORY[dates[0]].copy()

        # now we iterate through the remaining submissions that have been logged in the Journal,
        # as these just contain the changes that were submitted. 
        ### NB. we need to capture each subsequent submission!
        for item in dates[1:]:
            for change in history[item].keys():
                BASE_HISTORY[change] = history[item][change]
            
            # see above: because we chose to redundantly add the Timestamp into the 
            # Journal struct keys - redundant since it's used as a parent key to diffrentiate 
            # between edits - we no longer need to add more lines of code ... not sure if this was
            # the right call, but it's easy enough to comment this (and the earlier) line
            # and  to just go with the redundancy ... for more, see
            # https://github.com/signebedi/libreForms/issues/140.
            # BASE_HISTORY['Timestamp'] = item

            # finally we write this update to FULL_HISTORY dict
            FULL_HISTORY[item] = BASE_HISTORY.copy()


        return FULL_HISTORY

    except Exception as e:
        print(e)
        return None
```

**Comment by signebedi** [comment]
```
ERROR - Exception on /submissions/request/638ec83b46cf736a1e6a3bcd/history [GET] - 247399
Traceback (most recent call last):
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Approver'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/sig/Code/libreForms/app/submissions.py", line 565, in render_document_history
    display_data['Approval'].iloc[0] = set_digital_signature(username=db.session.query(User).filter_by(email=record['Approver'].iloc[0]).first().username,
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'Approver'

```

**Comment by signebedi** [comment]
Fixed in [cb4c459](https://github.com/signebedi/libreForms/commit/cb4c459cadb67a76cae5ea21dc02c9df55b5aa87). It was a logic issue - the `Approval` field needs to be not `None`. 

```python
# Added signature verification, see https://github.com/signebedi/libreForms/issues/144    
if 'Approval' in display_data.columns:
    if display_data['Approval'].iloc[0]:
        display_data['Approval'].iloc[0] = set_digital_signature(username=db.session.query(User).filter_by(email=display_data['Approver'].iloc[0]).first().username,
                        encrypted_string=display_data['Approval'].iloc[0])
    
    # After https://github.com/signebedi/libreForms/issues/145, adding this to ensure that
    # `Approval` is never None. 
    else:
        # display_data.drop(columns=['Approval'], inplace=True)
        display_data['Approval'].iloc[0] = "None"
```

**Comment by signebedi** [comment]
Fixed further in 4758076668c386bae23329696194aa551c69018c.
