### ISSUE TITLE
Allow administrators to define add'l, post-registration user fields

### ISSUE THREAD

**Issue by signebedi** [signebedi/libreForms#61]
Don't alter the registration process for now, I think it makes a lot of sense to keep that predictable and minimalist; instead, allow add'l user fields to be added. If we want to be anticipatory in how we implement, break it down by user roles

**Comment by signebedi** [comment]
Built a preliminary approach to this in 67e87eae1e936ae75f3454cdd60a711495bf27da.

**Comment by signebedi** [comment]
I believe I've fixed most of the issue raised above with e7cc52a60689ba2d7ced62b8236b7322fc4b2692, which modifies the logic such that new user fields are only introduced at the first time the application is run.

**Comment by signebedi** [comment]
Here's the test describing the problem identified above. I initialized a database. Then, I added a new field called `tensor` to the display variable. Then I restarted the app and received the following error:

```
2022-10-28 12:15:30 - ERROR - Exception on / [GET] - 507868
Traceback (most recent call last):
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: user.tensor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1521, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1861, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/sig/Code/libreForms/app/auth.py", line 308, in load_logged_in_user
    user_id = current_user.get_id()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/werkzeug/local.py", line 278, in __get__
    obj = instance._get_current_object()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/werkzeug/local.py", line 407, in _get_current_object
    return self.__local()  # type: ignore
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask_login/utils.py", line 384, in _get_user
    current_app.login_manager._load_user()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 355, in _load_user
    user = self._user_callback(user_id)
  File "/home/sig/Code/libreForms/app/__init__.py", line 168, in load_user
    return User.query.get(int(id))
  File "<string>", line 2, in get
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 402, in warned
    return fn(*args, **kwargs)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 943, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 947, in _get_impl
    return self.session._get_impl(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2912, in _get_impl
    return db_load_fn(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.tensor
[SQL: SELECT user.id AS user_id, user.email AS user_email, user.password AS user_password, user.username AS user_username, user.organization AS user_organization, user.phone AS user_phone, user.created_date AS user_created_date, user.specializations AS user_specializations, user.manager AS user_manager, user.tensor AS user_tensor, user.completed_jobs AS user_completed_jobs 
FROM user 
WHERE user.id = ?]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-10-28 12:15:30 - INFO - 127.0.0.1 - - [28/Oct/2022 12:15:30] "[35m[1mGET / HTTP/1.1[0m" 500 - - 507868
2022-10-28 12:15:30 - ERROR - Exception on /favicon.ico [GET] - 507868
Traceback (most recent call last):
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: user.tensor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1521, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1861, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/sig/Code/libreForms/app/auth.py", line 308, in load_logged_in_user
    user_id = current_user.get_id()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/werkzeug/local.py", line 278, in __get__
    obj = instance._get_current_object()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/werkzeug/local.py", line 407, in _get_current_object
    return self.__local()  # type: ignore
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask_login/utils.py", line 384, in _get_user
    current_app.login_manager._load_user()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 355, in _load_user
    user = self._user_callback(user_id)
  File "/home/sig/Code/libreForms/app/__init__.py", line 168, in load_user
    return User.query.get(int(id))
  File "<string>", line 2, in get
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 402, in warned
    return fn(*args, **kwargs)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 943, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 947, in _get_impl
    return self.session._get_impl(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2912, in _get_impl
    return db_load_fn(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.tensor
[SQL: SELECT user.id AS user_id, user.email AS user_email, user.password AS user_password, user.username AS user_username, user.organization AS user_organization, user.phone AS user_phone, user.created_date AS user_created_date, user.specializations AS user_specializations, user.manager AS user_manager, user.tensor AS user_tensor, user.completed_jobs AS user_completed_jobs 
FROM user 
WHERE user.id = ?]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

I think that the solution is to run a check like this each time the system restarts:

```
for FIELD in LIST_OF_USER_FIELDS:
  if FIELD not in TABLE:
    add FIELD to TABLE
```

Question: should we remove fields from the database that are no longer mentioned in the user config? Let's say we use a field called 'manager' but decide in the future to remove this field... do we want to remove this from the underlying database, or do we want  to use the display variable to determine which fields continue to be used in the web application, but leave all residual data in the database? I am inclined against removal of columns, and instead just telling the web application to only look at the fields defined in display.py.

**Comment by signebedi** [comment]
I think adding this homunculus to `__init__.py` may fix the problem:
```
    # borrowed from https://stackoverflow.com/a/17243132
    if display['user_registration_fields']:

        with app.app_context():

            def add_column(table_name, column, engine=db.engine):
                column_name = column.compile(dialect=engine.dialect)
                column_type = column.type.compile(engine.dialect)
                engine.execute('ALTER TABLE %s ADD COLUMN %s %s' % (table_name, column_name, column_type))


            # borrow from https://www.geeksforgeeks.org/python-sqlalchemy-get-column-names-dynamically/
            with db.engine.connect() as conn:
                result = conn.execute(f"SELECT * FROM user")
                cols = []
                for elem in result.cursor.description:
                    cols.append(elem[0])

            engine=db.engine
            for key, value in display['user_registration_fields'].items():
                    if key not in cols:
                        if value == str:
                            column = db.Column(key, db.String(1000))
                            add_column("user", column)

                        elif value == int:
                            column = db.Column(key, db.Column(db.Integer), primary_key=True)
                            add_column("user", column)

```

**Comment by signebedi** [comment]
In 843d93f907cb132ac7cde2cfb3de31176ce77fee, we added an empty reference to custom user fields in `templates/auth/profile.html`.

In the future, we should add similar logic to the registration page & bulk registration page.

**Comment by signebedi** [comment]
In afcce24a1a7e77c37e54e8d8e72d1b50765243f8, we added some very basic support in the user registration page, and slightly improved the API for custom user fields in hte display variable.

```python
    'user_registration_fields': {
        # 'specializations': ['SAS', 'Python', 'R', 'Stata', 'Javascript', 'FPDS'],
        # 'manager': ('Melinda Cordero', 'Grant Malley', 'Jerry Smith', 'Rick Sanchez'),
        # 'completed_jobs': 'hidden int',
        'specializations': {
          "type":str,
          "input_type":'autocomplete',
          "content":['SAS', 'Python', 'R', 'Stata', 'Javascript', 'FPDS'],
          "hidden":False,
          "default_value":"",
        },
        'manager': {
          "type":str,
          "hidden":False,
          "default_value":"",
        },
        'darby': {
          "type":str,
          "hidden":False,
          "default_value":"",
        },
        'completed_jobs': {
          "type":int,
          "hidden":True,
          "default_value":"", 
        },
    },

```

**Comment by signebedi** [comment]
In c34953c0c81f5c2046a3b287128c6e8939b49478, we 


```python
    'user_registration_fields': {
        'specializations': {
          "type":str,
          "default_value":"",
          "input_type":'checkbox',
          "content":['SAS', 'Python', 'R', 'Stata', 'Javascript', 'FPDS'],
          "required":True,
        },
        'manager': {
          "type":str,
          "input_type":'autocomplete',
          "content":['Jerry', 'Luke', 'Christina'],
          "required":False,
        },
        'tasks_completed': {
          "type":int,
          "input_type":'hidden',
          "content":[0],
          "required":False,
        },



```

**Comment by signebedi** [comment]
In c5d7fb83b437f22c250f6512205a1e65d455445e, added the backend support for this:


```python
TEMP = {}
for item in display['user_registration_fields'].keys():
    if display['user_registration_fields'][item]['input_type'] != 'hidden':
        TEMP[item] = request.form[item] 

...


new_user = User(
            email=email, 
            username=username.lower(), 
            password=generate_password_hash(password, method='sha256'),
            organization=organization,
            phone=phone,
            created_date=created_date,
            **TEMP,
        )

```

**Comment by signebedi** [comment]
We should update the bulk user upload code in `auth.py` to reflect potential custom user fields.

```python
# this is the download link for files in the temp directory
@bp.route('/download/<path:filename>')
@login_required
def download_bulk_user_template(filename='bulk_user_template.csv'):

    # this is our first stab at building templates, without accounting for nesting or repetition
    df = pd.DataFrame (columns=["username", "email", "password", "phone", "organization"])

    fp = os.path.join(tempfile_path, filename)
    df.to_csv(fp, index=False)

    return send_from_directory(tempfile_path,
                            filename, as_attachment=True)

```
