### ISSUE TITLE
Add support for bulk uploading local users

### ISSUE THREAD

**Issue by signebedi** [signebedi/libreForms#64]
For as long as this web application is primarily dependent on local authentication, it will be helpful to include some ways for administrators to efficiently manage users.

The first step to doing this is probably by allowing uploading user credentials from CSV.

Here is a starting spot:
1. https://stackoverflow.com/questions/2887878/importing-a-csv-file-into-a-sqlite3-database-table-using-python

Notably, however, we'll want to employ the SQL Alchemy API to make this process agnostic as to the SQL implementation used for the user database.

**Comment by signebedi** [comment]
Notably, it still fails when trying to add a user with a username (which are enforced as unique) that already exists in the user db...

```
2022-10-26 10:21:07 - ERROR - Exception on /auth/register/bulk [POST] - 409750
Traceback (most recent call last):
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sig/Code/libreForms/app/auth.py", line 235, in bulk_register
    db.session.commit()
  File "<string>", line 2, in commit
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3383, in flush
    self._flush(objects)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3523, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3483, in _flush
    flush_context.execute()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: INSERT INTO user (email, password, username, organization, phone, created_date) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('larry1@example.com', 'sha256$IjuqdDqGhLAHcGiM$f559398c9a7d5314a47ef5280a3a58cc217940632d08fa34262a1ccec5cefd4b', 'larry1', None, None, '2022-10-26 10:21:07')]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/sig/Code/libreForms/app/auth.py", line 240, in bulk_register
    log.error(f'{current_user.username.upper()} - failed to register new user {row.username.lower()} with email {row.email}.')
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 481, in __get__
    return self.impl.get(state, dict_)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 941, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 972, in _fire_loader_callables
    return state._load_expired(state, passive)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 712, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 1451, in load_scalar_attributes
    result = load_on_ident(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 407, in load_on_ident
    return load_on_pk_identity(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1711, in execute
    conn = self._connection_for_bind(bind)
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/home/sig/Code/libreForms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: INSERT INTO user (email, password, username, organization, phone, created_date) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('larry1@example.com', 'sha256$IjuqdDqGhLAHcGiM$f559398c9a7d5314a47ef5280a3a58cc217940632d08fa34262a1ccec5cefd4b', 'larry1', None, None, '2022-10-26 10:21:07')]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)

```

**Comment by signebedi** [comment]
Fixed in 41af3baa29a68eea4df32e43dd0127e19b0bec12 such that existing users are passed over, but those that do not exist are processed.

![image](https://user-images.githubusercontent.com/54920695/198348245-f52a80da-3167-45aa-bd3e-6ec174ffe6d5.png)

**Comment by signebedi** [comment]
Now that we've added signed URL email verification in #67  and custom user fields in #61 , we needed to update this functionality to account for both. We made the required changes in:

    https://github.com/signebedi/libreForms/commit/65b62e861a58d4899575774f966ea14d70b12f23
    https://github.com/signebedi/libreForms/commit/3f466dc25b2e12e70a01bd0825e229f8137e1046
